# https://github.com/lexik/LexikJWTAuthenticationBundle/tree/3.x/Resources/doc

lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 2.592e+6 # 30 days

  encoder:
    service: lexik_jwt_authentication.encoder.lcobucci
    signature_algorithm: RS512

  token_extractors:
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
